### ISSUE TITLE
raise AttributeError("Unknown IMAP4 command: '%s'" % attr)

### ISSUE THREAD

**Issue by Edtigoza** [vieterp/vieterp-mailbox#1]
Hi, good job,
thanks for you module.
I install it confirm email and when i try to **fetch Now** have this error
odoo 8

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/vieterp_mailbox/models/fetchmail_server.py", line 24, in fetch_mail
    result = super(vieterp_fetchmail_server, self).fetch_mail()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/fetchmail/fetchmail.py", line 262, in fetch_mail
    pop_server.quit()
  File "/usr/lib/python2.7/imaplib.py", line 223, in __getattr__
    raise AttributeError("Unknown IMAP4 command: '%s'" % attr)
AttributeError: Unknown IMAP4 command: 'quit'

Missing some dependency or I have done something wrong?

**Comment by tcakmak** [comment]
I have same problem. My odoo version is  10.0-20170514

**Comment by rizzopablo** [comment]
Same here.

**Comment by vikas-vg** [comment]
Issue is arising because in field `type` it's taking POP in place of IMAP.

**Comment by sabbane** [comment]
The same error here. Is there no workaround till the issue is fixed ?

**Comment by vikas-vg** [comment]
@sabbane use code from the pull request, it's fixed or use following [repository](https://github.com/sadavarti/vieterp-mailbox)

**Comment by sadavarti** [comment]
#2 Fix the issue

**Comment by drm** [comment]
I had a similar issue, using python3 instead of python2 fixed it for me.
